import struct
from collections import defaultdict

import netstruct
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, hmac


class Packet(object):

    # secret/ticket = b"" is byte object
    # secret: generated by admin, last ticket to be used
    # ticket: secret hashed n times (n == number of remaining tickets)
    # new secret = empty except when n == last ticket
    # user id
    ip = "" # type: String
    ticket = b"" # type: b""
    new_ticket = b"" # type: b""

    def __init__(self, ticket, ip, new_ticket=None):
        self.ip = ip
        self.ticket = ticket
        if new_ticket == None:
            self.new_ticket = b""
        else:
            self.new_ticket = new_ticket

    def pack(self, secret):
        # TODO secret should ideally be 256 bits
        # encoding defaults to utf8
        # secret is type: b""
        encoded_ip = self.ip.encode()
        # encoded_secret = secret.encode()

        # hmac signature from concat of encoded ticket and encoded ip 
        # signature = Packet._sign(encoded_secret, self.ticket, encoded_ip)
        signature = Packet._sign(secret, self.ticket, self.new_ticket, encoded_ip)

        # pack
        return netstruct.pack(b'!b$b$b$b$', self.ticket, self.new_ticket, encoded_ip, signature)

    @staticmethod
    def unpack(secret, buffer):
        ticket, new_ticket, ip, signature = netstruct.unpack(b'!b$b$b$b$', buffer)
        Packet._verify_signature(secret, ticket, new_ticket, ip, signature)
        return Packet(ticket, ip.decode(), new_ticket=new_ticket)

    @staticmethod
    def _verify_signature(secret, ticket, new_ticket, encoded_ip, signature):
        h = hmac.HMAC(secret, hashes.SHA256(), backend=default_backend())
        h.update(ticket + new_ticket + encoded_ip)
        return h.verify(signature)

    @staticmethod
    def _sign(secret, ticket, new_ticket, encoded_ip):
        h = hmac.HMAC(secret, hashes.SHA256(), backend=default_backend())
        to_sign = ticket + new_ticket + encoded_ip
        h.update(to_sign)
        return h.finalize()